apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-games-deployment
spec:
  selector:
    matchLabels:
      app: api-games
  template:
    metadata:
      labels:
        app: api-games
    spec:
      containers:
      - name: container-api-games
        image: viniciusdelr/videogames-service:latest 
        imagePullPolicy: Always 
        ports:
        - containerPort: 80 
        resources:
          requests:
            cpu: "100m"   # Reserva mínima (0.1 vCPU)
            memory: "128Mi"
          limits:
            cpu: "250m"   # Teto máximo (0.25 vCPU)
            memory: "256Mi"

        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config 
              key: ASPNETCORE_ENVIRONMENT
---
apiVersion: v1
kind: Service
metadata:
  name: servico-api-games
spec:
  type: ClusterIP 
  selector:
    app: api-games
  ports:
  - protocol: TCP
    port: 80      
    targetPort: 80 
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-games
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-games-deployment
  minReplicas: 1  
  maxReplicas: 10 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 