apiVersion: v1
kind: Secret
metadata:
  name: app-secrets 
type: Opaque
data:
  # As chaves aqui (ex: DatabaseConnection) devem bater com o "key" no seu Deployment.
  # O VALOR deve ser sua connection string convertida para Base64.
  
  # Exemplo: Connection string do SQL Server/Postgres
  DatabaseConnection: "U2VydmVyPXRjcDpmaWFwLXNxbC1zZXJ2ZXIuZGF0YWJhc2Uud2luZG93cy5uZXQ7SW5pdGlhbCBDYXRhbG9nPWRiLWZpYXBjbG91ZGdhbWVzO1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1GYWxzZTtVc2VyIElEPWFkbWluc3FsO1Bhc3N3b3JkPUFkbWluc2VydmVyMjAyNTtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9RmFsc2U7Q29ubmVjdGlvbiBUaW1lb3V0PTMwOw=="
  JwtSecret: "WW91clNlY3JldEtleTEyM3NlY3JldGtleWZvcmRlbW8="
  # Exemplo: Se usar RabbitMQ no futuro
  # RabbitMQConnection: "INSIRA_SUA_STRING_BASE64_AQUI"