apiVersion: v1
kind: Secret
metadata:
  name: app-secrets 
type: Opaque
data:

  DatabaseConnection: "U2VydmVyPXRjcDpmaWFwLXNxbC1zZXJ2ZXIuZGF0YWJhc2Uud2luZG93cy5uZXQ7SW5pdGlhbCBDYXRhbG9nPWRiLWZpYXBjbG91ZGdhbWVzO1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1GYWxzZTtVc2VyIElEPWFkbWluc3FsO1Bhc3N3b3JkPUFkbWluc2VydmVyMjAyNTtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9RmFsc2U7RW5jcnlwdD1UcnVlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9RmFsc2U7Q29ubmVjdGlvbiBUaW1lb3V0PTMwOw=="
  JwtSecret: "WW91clNlY3JldEtleTEyM3NlY3JldGtleWZvcmRlbW8="
  ServiceBusConnection: "RW5kcG9pbnQ9c2I6Ly9maWFwLWNsb3VkLWdhbWVzLWJ1cy5zZXJ2aWNlYnVzLndpbmRvd3MubmV0LztTaGFyZWRBY2Nlc3NLZXlOYW1lPVJvb3RNYW5hZ2VTaGFyZWRBY2Nlc3NLZXk7U2hhcmVkQWNjZXNzS2V5PVlzNVhQS040a0VYa2c1SGg5QytiQjBnc2pWdWhjaUhVSStBU2JCQzc0OWM9"
  appInsightsConnection: "SW5zdHJ1bWVudGF0aW9uS2V5PTM1NTQxN2RhLWU4ZGUtNDQ0OS1hNzY5LWRmYmUzNDM4YjgzYjtJbmdlc3Rpb25FbmRwb2ludD1odHRwczovL3dlc3R1czItMi5pbi5hcHBsaWNhdGlvbmluc2lnaHRzLmF6dXJlLmNvbS87TGl2ZUVuZHBvaW50PWh0dHBzOi8vd2VzdHVzMi5saXZlZGlhZ25vc3RpY3MubW9uaXRvci5henVyZS5jb20vO0FwcGxpY2F0aW9uSWQ9NTBlNzhlNmUtODUyMy00NTM0LTk1ZTQtZDU1NmU5OWFiMzc3"